### ISSUE TITLE
Postpone call for proposal deadline

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#120]
As titled. 

The exact date for the new CfP deadline will be discussed in the monthly meeting this Saturday.

**Comment by uranusjr** [comment]
:trollface:

**Comment by l34marr** [comment]
For English readers, the extended date/time is not explicitly shown with timezone and hh:mm info, that might cause confusion, right?

**Comment by uranusjr** [comment]
Good point. But since we never promised cfp will stop at midnight, there’s no need to specify time info IMO. Let’s just close cfp on *March 9* instead? As long as it’s after 7pm CST there can be no disputes (Taipei is +8, so the latest midnight, -11, is 19 hours after ours).

What do you say @ccwang002?

**Comment by ccwang002** [comment]
Officially, we close the Call for Proposal at Mar 8 23:59:59 UTC+8. That
said, we will update the production server to stop accepting new
proposals on Mar 9 (noon probably).

P.S. Using CST will cause many confusion for US people. Both Asia/Taipei
and US/Central timezone can be abbreviated as CST.

**Comment by l34marr** [comment]
Stop by Mar 9 noon seems good enough for me.
